# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ColumnsEditor_UI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog_columnsEditor(object):
    def setupUi(self, dialog_columnsEditor):
        dialog_columnsEditor.setObjectName("dialog_columnsEditor")
        dialog_columnsEditor.resize(950, 457)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog_columnsEditor.sizePolicy().hasHeightForWidth())
        dialog_columnsEditor.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(dialog_columnsEditor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(dialog_columnsEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(145, 360))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.combobox_columns_type = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combobox_columns_type.setFont(font)
        self.combobox_columns_type.setObjectName("combobox_columns_type")
        self.combobox_columns_type.addItem("")
        self.combobox_columns_type.addItem("")
        self.combobox_columns_type.addItem("")
        self.verticalLayout.addWidget(self.combobox_columns_type)
        self.listwidget_columns_variables = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwidget_columns_variables.sizePolicy().hasHeightForWidth())
        self.listwidget_columns_variables.setSizePolicy(sizePolicy)
        self.listwidget_columns_variables.setMinimumSize(QtCore.QSize(140, 0))
        self.listwidget_columns_variables.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.listwidget_columns_variables.setFont(font)
        self.listwidget_columns_variables.setDragEnabled(True)
        self.listwidget_columns_variables.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.listwidget_columns_variables.setObjectName("listwidget_columns_variables")
        self.verticalLayout.addWidget(self.listwidget_columns_variables)
        self.listwidget_columns_formulas = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwidget_columns_formulas.sizePolicy().hasHeightForWidth())
        self.listwidget_columns_formulas.setSizePolicy(sizePolicy)
        self.listwidget_columns_formulas.setMinimumSize(QtCore.QSize(140, 140))
        self.listwidget_columns_formulas.setMaximumSize(QtCore.QSize(140, 240))
        self.listwidget_columns_formulas.setDragEnabled(True)
        self.listwidget_columns_formulas.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.listwidget_columns_formulas.setObjectName("listwidget_columns_formulas")
        self.verticalLayout.addWidget(self.listwidget_columns_formulas)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.groupBox_2 = QtWidgets.QGroupBox(dialog_columnsEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(650, 360))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 360))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_SaveColumns = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_SaveColumns.sizePolicy().hasHeightForWidth())
        self.button_SaveColumns.setSizePolicy(sizePolicy)
        self.button_SaveColumns.setMinimumSize(QtCore.QSize(600, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.button_SaveColumns.setFont(font)
        self.button_SaveColumns.setObjectName("button_SaveColumns")
        self.gridLayout_3.addWidget(self.button_SaveColumns, 1, 0, 1, 1)
        self.listwidget_columnsEdit = ListWidget_DropVariables(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwidget_columnsEdit.sizePolicy().hasHeightForWidth())
        self.listwidget_columnsEdit.setSizePolicy(sizePolicy)
        self.listwidget_columnsEdit.setMinimumSize(QtCore.QSize(600, 65))
        self.listwidget_columnsEdit.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.listwidget_columnsEdit.setFont(font)
        self.listwidget_columnsEdit.setDragEnabled(True)
        self.listwidget_columnsEdit.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listwidget_columnsEdit.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listwidget_columnsEdit.setFlow(QtWidgets.QListView.LeftToRight)
        self.listwidget_columnsEdit.setModelColumn(0)
        self.listwidget_columnsEdit.setObjectName("listwidget_columnsEdit")
        self.gridLayout_3.addWidget(self.listwidget_columnsEdit, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1, QtCore.Qt.AlignTop)

        self.retranslateUi(dialog_columnsEditor)
        QtCore.QMetaObject.connectSlotsByName(dialog_columnsEditor)

    def retranslateUi(self, dialog_columnsEditor):
        _translate = QtCore.QCoreApplication.translate
        dialog_columnsEditor.setWindowTitle(_translate("dialog_columnsEditor", "Configuração de Colunas"))
        self.groupBox.setTitle(_translate("dialog_columnsEditor", "VARIÁVEIS"))
        self.combobox_columns_type.setItemText(0, _translate("dialog_columnsEditor", "WELLS"))
        self.combobox_columns_type.setItemText(1, _translate("dialog_columnsEditor", "GROUPS"))
        self.combobox_columns_type.setItemText(2, _translate("dialog_columnsEditor", "SECTORS"))
        self.groupBox_2.setTitle(_translate("dialog_columnsEditor", "COLUNAS PARA ORDENAR E RENOMEAR"))
        self.button_SaveColumns.setText(_translate("dialog_columnsEditor", "Salvar"))

from Interface.Extras.CustomWidgets import ListWidget_DropVariables

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_columnsEditor = QtWidgets.QDialog()
    ui = Ui_dialog_columnsEditor()
    ui.setupUi(dialog_columnsEditor)
    dialog_columnsEditor.show()
    sys.exit(app.exec_())

