# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DatesEditor_UI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog_datesEditor(object):
    def setupUi(self, dialog_datesEditor):
        dialog_datesEditor.setObjectName("dialog_datesEditor")
        dialog_datesEditor.resize(243, 332)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog_datesEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radiobutton_DatesEditor_Curvas = QtWidgets.QGroupBox(dialog_datesEditor)
        self.radiobutton_DatesEditor_Curvas.setTitle("")
        self.radiobutton_DatesEditor_Curvas.setObjectName("radiobutton_DatesEditor_Curvas")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.radiobutton_DatesEditor_Curvas)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radiobutton_DatesEditor_Graph = QtWidgets.QRadioButton(self.radiobutton_DatesEditor_Curvas)
        self.radiobutton_DatesEditor_Graph.setObjectName("radiobutton_DatesEditor_Graph")
        self.horizontalLayout.addWidget(self.radiobutton_DatesEditor_Graph)
        self.radiobutton_DatesEditor_Table = QtWidgets.QRadioButton(self.radiobutton_DatesEditor_Curvas)
        self.radiobutton_DatesEditor_Table.setObjectName("radiobutton_DatesEditor_Table")
        self.horizontalLayout.addWidget(self.radiobutton_DatesEditor_Table)
        self.gridLayout_4.addWidget(self.radiobutton_DatesEditor_Curvas, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(dialog_datesEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(220, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_deleteDayofMonth = QtWidgets.QPushButton(self.groupBox_2)
        self.button_deleteDayofMonth.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_deleteDayofMonth.setIcon(icon)
        self.button_deleteDayofMonth.setIconSize(QtCore.QSize(22, 22))
        self.button_deleteDayofMonth.setObjectName("button_deleteDayofMonth")
        self.gridLayout_2.addWidget(self.button_deleteDayofMonth, 1, 3, 1, 1)
        self.lineedit_dayofMonth = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_dayofMonth.sizePolicy().hasHeightForWidth())
        self.lineedit_dayofMonth.setSizePolicy(sizePolicy)
        self.lineedit_dayofMonth.setMinimumSize(QtCore.QSize(40, 0))
        self.lineedit_dayofMonth.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineedit_dayofMonth.setObjectName("lineedit_dayofMonth")
        self.gridLayout_2.addWidget(self.lineedit_dayofMonth, 1, 0, 1, 1)
        self.button_addDayofMonth = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_addDayofMonth.sizePolicy().hasHeightForWidth())
        self.button_addDayofMonth.setSizePolicy(sizePolicy)
        self.button_addDayofMonth.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_addDayofMonth.setIcon(icon1)
        self.button_addDayofMonth.setIconSize(QtCore.QSize(24, 24))
        self.button_addDayofMonth.setObjectName("button_addDayofMonth")
        self.gridLayout_2.addWidget(self.button_addDayofMonth, 1, 1, 1, 1)
        self.listwidget_daysofMonth = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwidget_daysofMonth.sizePolicy().hasHeightForWidth())
        self.listwidget_daysofMonth.setSizePolicy(sizePolicy)
        self.listwidget_daysofMonth.setMinimumSize(QtCore.QSize(45, 80))
        self.listwidget_daysofMonth.setMaximumSize(QtCore.QSize(45, 80))
        self.listwidget_daysofMonth.setObjectName("listwidget_daysofMonth")
        self.gridLayout_2.addWidget(self.listwidget_daysofMonth, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 3, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(dialog_datesEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(220, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineedit_startDate = LineEdit_DateMask(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_startDate.sizePolicy().hasHeightForWidth())
        self.lineedit_startDate.setSizePolicy(sizePolicy)
        self.lineedit_startDate.setMinimumSize(QtCore.QSize(75, 0))
        self.lineedit_startDate.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineedit_startDate.setObjectName("lineedit_startDate")
        self.gridLayout.addWidget(self.lineedit_startDate, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineedit_endDate = LineEdit_DateMask(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_endDate.sizePolicy().hasHeightForWidth())
        self.lineedit_endDate.setSizePolicy(sizePolicy)
        self.lineedit_endDate.setMinimumSize(QtCore.QSize(75, 0))
        self.lineedit_endDate.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineedit_endDate.setObjectName("lineedit_endDate")
        self.gridLayout.addWidget(self.lineedit_endDate, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 2, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(dialog_datesEditor)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkbox_alldates = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkbox_alldates.setObjectName("checkbox_alldates")
        self.verticalLayout_2.addWidget(self.checkbox_alldates)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.button_saveDates = QtWidgets.QPushButton(dialog_datesEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_saveDates.sizePolicy().hasHeightForWidth())
        self.button_saveDates.setSizePolicy(sizePolicy)
        self.button_saveDates.setMinimumSize(QtCore.QSize(220, 0))
        self.button_saveDates.setMaximumSize(QtCore.QSize(220, 16777215))
        self.button_saveDates.setObjectName("button_saveDates")
        self.verticalLayout.addWidget(self.button_saveDates)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(dialog_datesEditor)
        QtCore.QMetaObject.connectSlotsByName(dialog_datesEditor)
        dialog_datesEditor.setTabOrder(self.radiobutton_DatesEditor_Graph, self.radiobutton_DatesEditor_Table)
        dialog_datesEditor.setTabOrder(self.radiobutton_DatesEditor_Table, self.checkbox_alldates)
        dialog_datesEditor.setTabOrder(self.checkbox_alldates, self.lineedit_startDate)
        dialog_datesEditor.setTabOrder(self.lineedit_startDate, self.lineedit_endDate)
        dialog_datesEditor.setTabOrder(self.lineedit_endDate, self.lineedit_dayofMonth)
        dialog_datesEditor.setTabOrder(self.lineedit_dayofMonth, self.button_addDayofMonth)
        dialog_datesEditor.setTabOrder(self.button_addDayofMonth, self.button_saveDates)
        dialog_datesEditor.setTabOrder(self.button_saveDates, self.listwidget_daysofMonth)
        dialog_datesEditor.setTabOrder(self.listwidget_daysofMonth, self.button_deleteDayofMonth)

    def retranslateUi(self, dialog_datesEditor):
        _translate = QtCore.QCoreApplication.translate
        dialog_datesEditor.setWindowTitle(_translate("dialog_datesEditor", "Configuração de Datas"))
        self.radiobutton_DatesEditor_Graph.setText(_translate("dialog_datesEditor", "Curvas"))
        self.radiobutton_DatesEditor_Table.setText(_translate("dialog_datesEditor", "Tabelas"))
        self.label.setText(_translate("dialog_datesEditor", "Dias do mês"))
        self.label_2.setText(_translate("dialog_datesEditor", "Início"))
        self.label_3.setText(_translate("dialog_datesEditor", "Fim"))
        self.checkbox_alldates.setText(_translate("dialog_datesEditor", "selecionar todas as datas disponíveis"))
        self.button_saveDates.setText(_translate("dialog_datesEditor", "Salvar"))

from Interface.Extras.CustomWidgets import LineEdit_DateMask

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_datesEditor = QtWidgets.QDialog()
    ui = Ui_dialog_datesEditor()
    ui.setupUi(dialog_datesEditor)
    dialog_datesEditor.show()
    sys.exit(app.exec_())

