# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResReporter_UI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QMain_ResReporter(object):
    def setupUi(self, QMain_ResReporter):
        QMain_ResReporter.setObjectName("QMain_ResReporter")
        QMain_ResReporter.resize(1107, 714)
        self.centralwidget = QtWidgets.QWidget(QMain_ResReporter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(900, 100))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 908, 108))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listwidget_ModelsAdded = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwidget_ModelsAdded.sizePolicy().hasHeightForWidth())
        self.listwidget_ModelsAdded.setSizePolicy(sizePolicy)
        self.listwidget_ModelsAdded.setMinimumSize(QtCore.QSize(890, 90))
        self.listwidget_ModelsAdded.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listwidget_ModelsAdded.setFlow(QtWidgets.QListView.TopToBottom)
        self.listwidget_ModelsAdded.setViewMode(QtWidgets.QListView.ListMode)
        self.listwidget_ModelsAdded.setObjectName("listwidget_ModelsAdded")
        self.horizontalLayout_2.addWidget(self.listwidget_ModelsAdded)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 1, 1, 1)
        self.button_DeleteModel = QtWidgets.QPushButton(self.centralwidget)
        self.button_DeleteModel.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_DeleteModel.setIcon(icon)
        self.button_DeleteModel.setObjectName("button_DeleteModel")
        self.gridLayout.addWidget(self.button_DeleteModel, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(275, 0))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_graphs = QtWidgets.QWidget()
        self.tab_graphs.setObjectName("tab_graphs")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_graphs)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_graphs)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1063, 439))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_graphListWidget = QtWidgets.QVBoxLayout()
        self.verticalLayout_graphListWidget.setObjectName("verticalLayout_graphListWidget")
        self.verticalLayout_3.addLayout(self.verticalLayout_graphListWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.button_NewGraph = QtWidgets.QPushButton(self.tab_graphs)
        self.button_NewGraph.setObjectName("button_NewGraph")
        self.verticalLayout_4.addWidget(self.button_NewGraph)
        self.button_ReportGraphs = QtWidgets.QPushButton(self.tab_graphs)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_ReportGraphs.setFont(font)
        self.button_ReportGraphs.setObjectName("button_ReportGraphs")
        self.verticalLayout_4.addWidget(self.button_ReportGraphs)
        self.tabWidget.addTab(self.tab_graphs, "")
        self.tab_tables = QtWidgets.QWidget()
        self.tab_tables.setObjectName("tab_tables")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_tables)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_tables)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1063, 332))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_setListWidget = QtWidgets.QVBoxLayout()
        self.verticalLayout_setListWidget.setObjectName("verticalLayout_setListWidget")
        self.verticalLayout_8.addLayout(self.verticalLayout_setListWidget)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.addWidget(self.scrollArea_3)
        self.button_NewSet = QtWidgets.QPushButton(self.tab_tables)
        self.button_NewSet.setObjectName("button_NewSet")
        self.verticalLayout_6.addWidget(self.button_NewSet)
        self.button_prepareTable = QtWidgets.QPushButton(self.tab_tables)
        self.button_prepareTable.setObjectName("button_prepareTable")
        self.verticalLayout_6.addWidget(self.button_prepareTable)
        self.scrollarea_TableHeaders = QtWidgets.QScrollArea(self.tab_tables)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollarea_TableHeaders.sizePolicy().hasHeightForWidth())
        self.scrollarea_TableHeaders.setSizePolicy(sizePolicy)
        self.scrollarea_TableHeaders.setMinimumSize(QtCore.QSize(0, 60))
        self.scrollarea_TableHeaders.setMaximumSize(QtCore.QSize(16777215, 60))
        self.scrollarea_TableHeaders.setWidgetResizable(True)
        self.scrollarea_TableHeaders.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollarea_TableHeaders.setObjectName("scrollarea_TableHeaders")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1046, 68))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listwidget_tableHeaders = QtWidgets.QListWidget(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwidget_tableHeaders.sizePolicy().hasHeightForWidth())
        self.listwidget_tableHeaders.setSizePolicy(sizePolicy)
        self.listwidget_tableHeaders.setMinimumSize(QtCore.QSize(0, 50))
        self.listwidget_tableHeaders.setMaximumSize(QtCore.QSize(16777215, 50))
        self.listwidget_tableHeaders.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listwidget_tableHeaders.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listwidget_tableHeaders.setFlow(QtWidgets.QListView.LeftToRight)
        self.listwidget_tableHeaders.setObjectName("listwidget_tableHeaders")
        self.gridLayout_2.addWidget(self.listwidget_tableHeaders, 0, 0, 1, 1)
        self.scrollarea_TableHeaders.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_6.addWidget(self.scrollarea_TableHeaders)
        self.button_ReportSets = QtWidgets.QPushButton(self.tab_tables)
        self.button_ReportSets.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_ReportSets.setFont(font)
        self.button_ReportSets.setObjectName("button_ReportSets")
        self.verticalLayout_6.addWidget(self.button_ReportSets)
        self.tabWidget.addTab(self.tab_tables, "")
        self.verticalLayout.addWidget(self.tabWidget)
        QMain_ResReporter.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(QMain_ResReporter)
        self.statusbar.setObjectName("statusbar")
        QMain_ResReporter.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(QMain_ResReporter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Templates = QtWidgets.QMenu(self.menubar)
        self.menu_Templates.setObjectName("menu_Templates")
        self.menu_Models = QtWidgets.QMenu(self.menubar)
        self.menu_Models.setObjectName("menu_Models")
        self.menu_Configs = QtWidgets.QMenu(self.menubar)
        self.menu_Configs.setObjectName("menu_Configs")
        QMain_ResReporter.setMenuBar(self.menubar)
        self.action_SaveTemplate = QtWidgets.QAction(QMain_ResReporter)
        self.action_SaveTemplate.setObjectName("action_SaveTemplate")
        self.action_ImportTemplate = QtWidgets.QAction(QMain_ResReporter)
        self.action_ImportTemplate.setObjectName("action_ImportTemplate")
        self.action_AddModels = QtWidgets.QAction(QMain_ResReporter)
        self.action_AddModels.setObjectName("action_AddModels")
        self.action_ConfigUnits = QtWidgets.QAction(QMain_ResReporter)
        self.action_ConfigUnits.setObjectName("action_ConfigUnits")
        self.action_ConfigFormulas = QtWidgets.QAction(QMain_ResReporter)
        self.action_ConfigFormulas.setObjectName("action_ConfigFormulas")
        self.action_ConfigUnit = QtWidgets.QAction(QMain_ResReporter)
        self.action_ConfigUnit.setObjectName("action_ConfigUnit")
        self.action_ConfigDates = QtWidgets.QAction(QMain_ResReporter)
        self.action_ConfigDates.setObjectName("action_ConfigDates")
        self.action_ConfigColumns = QtWidgets.QAction(QMain_ResReporter)
        self.action_ConfigColumns.setObjectName("action_ConfigColumns")
        self.menu_Templates.addAction(self.action_SaveTemplate)
        self.menu_Templates.addAction(self.action_ImportTemplate)
        self.menu_Models.addAction(self.action_AddModels)
        self.menu_Configs.addAction(self.action_ConfigFormulas)
        self.menu_Configs.addAction(self.action_ConfigUnit)
        self.menu_Configs.addAction(self.action_ConfigDates)
        self.menu_Configs.addAction(self.action_ConfigColumns)
        self.menubar.addAction(self.menu_Models.menuAction())
        self.menubar.addAction(self.menu_Templates.menuAction())
        self.menubar.addAction(self.menu_Configs.menuAction())

        self.retranslateUi(QMain_ResReporter)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(QMain_ResReporter)

    def retranslateUi(self, QMain_ResReporter):
        _translate = QtCore.QCoreApplication.translate
        QMain_ResReporter.setWindowTitle(_translate("QMain_ResReporter", "RES REPORTER"))
        self.label.setText(_translate("QMain_ResReporter", "Modelos Adicionados"))
        self.button_DeleteModel.setToolTip(_translate("QMain_ResReporter", "Excluir modelo"))
        self.button_NewGraph.setToolTip(_translate("QMain_ResReporter", "Adicionar nova curva"))
        self.button_NewGraph.setText(_translate("QMain_ResReporter", "+ CURVAS"))
        self.button_ReportGraphs.setToolTip(_translate("QMain_ResReporter", "Gerar curvas e exportar para (??)"))
        self.button_ReportGraphs.setText(_translate("QMain_ResReporter", "GERAR CURVAS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_graphs), _translate("QMain_ResReporter", "Curvas"))
        self.button_NewSet.setToolTip(_translate("QMain_ResReporter", "Adicionar novo conjunto de dados"))
        self.button_NewSet.setText(_translate("QMain_ResReporter", "+ DADOS"))
        self.button_prepareTable.setText(_translate("QMain_ResReporter", "Preparar Tabela"))
        self.listwidget_tableHeaders.setSortingEnabled(False)
        self.button_ReportSets.setToolTip(_translate("QMain_ResReporter", "Gerar tabela e exportar para .xlsx"))
        self.button_ReportSets.setText(_translate("QMain_ResReporter", "EXPORTAR TABELA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tables), _translate("QMain_ResReporter", "Tabelas"))
        self.menu_Templates.setTitle(_translate("QMain_ResReporter", "Template"))
        self.menu_Models.setTitle(_translate("QMain_ResReporter", "Modelos"))
        self.menu_Configs.setTitle(_translate("QMain_ResReporter", "Configurações"))
        self.action_SaveTemplate.setText(_translate("QMain_ResReporter", "Salvar Template"))
        self.action_ImportTemplate.setText(_translate("QMain_ResReporter", "Importar Template"))
        self.action_AddModels.setText(_translate("QMain_ResReporter", "Adicionar Modelos"))
        self.action_ConfigUnits.setText(_translate("QMain_ResReporter", "Configurar unidades"))
        self.action_ConfigFormulas.setText(_translate("QMain_ResReporter", "Configurar fórmulas"))
        self.action_ConfigUnit.setText(_translate("QMain_ResReporter", "Configurar unidades"))
        self.action_ConfigDates.setText(_translate("QMain_ResReporter", "Configurar datas"))
        self.action_ConfigColumns.setText(_translate("QMain_ResReporter", "Configurar colunas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QMain_ResReporter = QtWidgets.QMainWindow()
    ui = Ui_QMain_ResReporter()
    ui.setupUi(QMain_ResReporter)
    QMain_ResReporter.show()
    sys.exit(app.exec_())

