# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UnitsEditor_UI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog_unitsEditor(object):
    def setupUi(self, dialog_unitsEditor):
        dialog_unitsEditor.setObjectName("dialog_unitsEditor")
        dialog_unitsEditor.resize(585, 390)
        self.gridLayout = QtWidgets.QGridLayout(dialog_unitsEditor)
        self.gridLayout.setObjectName("gridLayout")
        self.combobox_timeseriesType = QtWidgets.QComboBox(dialog_unitsEditor)
        self.combobox_timeseriesType.setObjectName("combobox_timeseriesType")
        self.combobox_timeseriesType.addItem("")
        self.combobox_timeseriesType.addItem("")
        self.combobox_timeseriesType.addItem("")
        self.gridLayout.addWidget(self.combobox_timeseriesType, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(dialog_unitsEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(160, 340))
        self.scrollArea.setMaximumSize(QtCore.QSize(160, 340))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 158, 348))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listwidget_variables = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwidget_variables.sizePolicy().hasHeightForWidth())
        self.listwidget_variables.setSizePolicy(sizePolicy)
        self.listwidget_variables.setMinimumSize(QtCore.QSize(140, 330))
        self.listwidget_variables.setMaximumSize(QtCore.QSize(140, 330))
        self.listwidget_variables.setObjectName("listwidget_variables")
        self.verticalLayout.addWidget(self.listwidget_variables)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.widget_configUnit = QtWidgets.QWidget(dialog_unitsEditor)
        self.widget_configUnit.setObjectName("widget_configUnit")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_configUnit)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridlayout_configUnit = QtWidgets.QGridLayout()
        self.gridlayout_configUnit.setObjectName("gridlayout_configUnit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_configUnit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.lineedit_unitName_new = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_unitName_new.sizePolicy().hasHeightForWidth())
        self.lineedit_unitName_new.setSizePolicy(sizePolicy)
        self.lineedit_unitName_new.setMinimumSize(QtCore.QSize(100, 0))
        self.lineedit_unitName_new.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineedit_unitName_new.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineedit_unitName_new.setObjectName("lineedit_unitName_new")
        self.gridLayout_5.addWidget(self.lineedit_unitName_new, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineedit_unitMultplier = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_unitMultplier.sizePolicy().hasHeightForWidth())
        self.lineedit_unitMultplier.setSizePolicy(sizePolicy)
        self.lineedit_unitMultplier.setMinimumSize(QtCore.QSize(100, 0))
        self.lineedit_unitMultplier.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineedit_unitMultplier.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineedit_unitMultplier.setObjectName("lineedit_unitMultplier")
        self.gridLayout_5.addWidget(self.lineedit_unitMultplier, 1, 1, 1, 1)
        self.gridlayout_configUnit.addWidget(self.groupBox_2, 2, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout_configUnit.addItem(spacerItem1, 4, 1, 1, 1)
        self.button_SaveUnit = QtWidgets.QPushButton(self.widget_configUnit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_SaveUnit.sizePolicy().hasHeightForWidth())
        self.button_SaveUnit.setSizePolicy(sizePolicy)
        self.button_SaveUnit.setMinimumSize(QtCore.QSize(300, 0))
        self.button_SaveUnit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.button_SaveUnit.setObjectName("button_SaveUnit")
        self.gridlayout_configUnit.addWidget(self.button_SaveUnit, 3, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.widget_configUnit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(310, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(310, 16777215))
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_variable = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_variable.sizePolicy().hasHeightForWidth())
        self.lbl_variable.setSizePolicy(sizePolicy)
        self.lbl_variable.setMinimumSize(QtCore.QSize(300, 40))
        self.lbl_variable.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_variable.setFont(font)
        self.lbl_variable.setText("")
        self.lbl_variable.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_variable.setObjectName("lbl_variable")
        self.gridLayout_4.addWidget(self.lbl_variable, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lbl_unitName_orignal = QtWidgets.QLabel(self.groupBox)
        self.lbl_unitName_orignal.setText("")
        self.lbl_unitName_orignal.setObjectName("lbl_unitName_orignal")
        self.horizontalLayout.addWidget(self.lbl_unitName_orignal)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridlayout_configUnit.addWidget(self.groupBox, 0, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridlayout_configUnit)
        self.gridLayout.addWidget(self.widget_configUnit, 1, 1, 1, 1)

        self.retranslateUi(dialog_unitsEditor)
        self.listwidget_variables.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(dialog_unitsEditor)
        dialog_unitsEditor.setTabOrder(self.lineedit_unitName_new, self.lineedit_unitMultplier)
        dialog_unitsEditor.setTabOrder(self.lineedit_unitMultplier, self.button_SaveUnit)
        dialog_unitsEditor.setTabOrder(self.button_SaveUnit, self.listwidget_variables)
        dialog_unitsEditor.setTabOrder(self.listwidget_variables, self.combobox_timeseriesType)
        dialog_unitsEditor.setTabOrder(self.combobox_timeseriesType, self.scrollArea)

    def retranslateUi(self, dialog_unitsEditor):
        _translate = QtCore.QCoreApplication.translate
        dialog_unitsEditor.setWindowTitle(_translate("dialog_unitsEditor", "Configuração de Unidades"))
        self.combobox_timeseriesType.setItemText(0, _translate("dialog_unitsEditor", "WELLS"))
        self.combobox_timeseriesType.setItemText(1, _translate("dialog_unitsEditor", "GROUPS"))
        self.combobox_timeseriesType.setItemText(2, _translate("dialog_unitsEditor", "SECTORS"))
        self.label.setText(_translate("dialog_unitsEditor", "Nova Unidade:"))
        self.label_2.setText(_translate("dialog_unitsEditor", "Multiplicador:"))
        self.button_SaveUnit.setText(_translate("dialog_unitsEditor", "salvar"))
        self.label_3.setText(_translate("dialog_unitsEditor", "Unidade Original:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_unitsEditor = QtWidgets.QDialog()
    ui = Ui_dialog_unitsEditor()
    ui.setupUi(dialog_unitsEditor)
    dialog_unitsEditor.show()
    sys.exit(app.exec_())

